### ISSUE TITLE
Logger

### ISSUE THREAD

**Issue by xalgord** [CYS4srl/SensitiveDiscoverer#33] opened 2023-08-28 15:57 UTC
Hi,
Is it possible to fetch logger history install of HTTP history?

**Comment by beryxz** [comment] 2023-08-28 16:15
Duplicate of #3 

It would be nice, but it seems Burp doesn't allow for this in extensions.
I'm open to suggestions on this matter.

**Closed** 2023-09-06 06:18 UTC
Labels: duplicate, feature/logger
